from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

from ..models import Note

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(text: str) -> str:
    return _SLUG_RE.sub("-", text.lower()).strip("-") or "untitled"


class KarpathyWikiRenderer:
    """Render notes as a Karpathy-style Markdown wiki: a flat index page,
    one page per category, and lightweight `[[backlinks]]` between notes
    that share at least `backlink_min_shared_tags` tags.
    """

    def __init__(self, backlink_min_shared_tags: int = 2) -> None:
        self._min_shared = backlink_min_shared_tags

    def render(self, notes: list[Note], out_dir: Path) -> None:
        out_dir.mkdir(parents=True, exist_ok=True)

        for stale in out_dir.glob("*.md"):
            stale.unlink()

        by_category: dict[str, list[Note]] = defaultdict(list)
        for note in notes:
            by_category[note.category].append(note)

        self._write_index(by_category, out_dir)
        for category, items in by_category.items():
            self._write_category(category, items, notes, out_dir)

    def _write_index(self, by_category: dict[str, list[Note]], out_dir: Path) -> None:
        lines = [
            "# Notes Wiki",
            "",
            "_Auto-generated by SuperNoteOrganiser. Each note carries an "
            "**Action / Why / Purpose** block that distils the note's reasoning into "
            "something you can actually do._",
            "",
            "## Categories",
            "",
        ]
        for category in sorted(by_category):
            count = len(by_category[category])
            lines.append(f"- [{category}]({slugify(category)}.md) — {count} note{'s' if count != 1 else ''}")
        lines.append("")
        (out_dir / "index.md").write_text("\n".join(lines), encoding="utf-8")

    def _write_category(
        self,
        category: str,
        items: list[Note],
        all_notes: list[Note],
        out_dir: Path,
    ) -> None:
        lines = [f"# {category}", "", f"[← index](index.md)", ""]
        for note in sorted(items, key=lambda n: n.title.lower()):
            lines.extend(self._render_note(note, all_notes))
            lines.append("")
        path = out_dir / f"{slugify(category)}.md"
        path.write_text("\n".join(lines), encoding="utf-8")

    def _render_note(self, note: Note, all_notes: list[Note]) -> list[str]:
        out: list[str] = [f"## {note.title}", ""]
        if note.summary:
            out.extend([f"_{note.summary}_", ""])
        out.extend([note.body.strip(), ""])
        out.extend(
            [
                f"**Action:** {note.action.action}",
                f"**Why:** {note.action.why}",
                f"**Purpose:** {note.action.purpose}",
                "",
            ]
        )

        if note.versions:
            out.append("### Versions")
            for i, v in enumerate(note.versions, 1):
                out.append(f"- **v{i}:** {v.strip()}")
            out.append("")

        backlinks = self._backlinks_for(note, all_notes)
        meta_bits: list[str] = []
        if note.tags:
            meta_bits.append("Tags: " + " ".join(f"#{t}" for t in note.tags))
        if note.sources:
            meta_bits.append("Sources: " + ", ".join(sorted(set(note.sources))))
        if note.devices:
            meta_bits.append("Devices: " + ", ".join(sorted(set(note.devices))))
        if backlinks:
            meta_bits.append("See also: " + ", ".join(f"[[{t}]]" for t in backlinks))
        if meta_bits:
            out.append("> " + " · ".join(meta_bits))
            out.append("")
        return out

    def _backlinks_for(self, note: Note, all_notes: list[Note]) -> list[str]:
        my_tags = set(note.tags)
        if not my_tags:
            return []
        related: list[str] = []
        for other in all_notes:
            if other.note_id == note.note_id:
                continue
            shared = my_tags & set(other.tags)
            if len(shared) >= self._min_shared:
                related.append(other.title)
        return sorted(related)[:5]
