from __future__ import annotations

import html
import re
from collections import defaultdict
from pathlib import Path

from ..models import Note

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(text: str) -> str:
    return _SLUG_RE.sub("-", text.lower()).strip("-") or "untitled"


def _section_html(kind: str, label: str, body_html: str) -> str:
    """Emit one labelled section. `kind` selects the side-border colour
    via the `nb nb-{kind}` class pair styled in app.py's CSS."""
    return (
        f'<div class="nb nb-{kind}">'
        f'<div class="nb-l">{html.escape(label)}</div>'
        f'<div class="nb-b">{body_html}</div>'
        f'</div>'
    )


class KarpathyWikiRenderer:
    """Render notes as a Karpathy-style Markdown wiki: a flat index page,
    one page per category, and lightweight `[[backlinks]]` between notes
    that share at least `backlink_min_shared_tags` tags.
    """

    def __init__(self, backlink_min_shared_tags: int = 2) -> None:
        self._min_shared = backlink_min_shared_tags

    def render(self, notes: list[Note], out_dir: Path) -> None:
        out_dir.mkdir(parents=True, exist_ok=True)

        for stale in out_dir.glob("*.md"):
            stale.unlink()

        by_category: dict[str, list[Note]] = defaultdict(list)
        for note in notes:
            by_category[note.category].append(note)

        self._write_index(by_category, out_dir)
        for category, items in by_category.items():
            self._write_category(category, items, notes, out_dir)

    def _write_index(self, by_category: dict[str, list[Note]], out_dir: Path) -> None:
        lines = [
            "# Notes Wiki",
            "",
            "_Auto-generated by SuperNoteOrganiser. Each note carries an "
            "**Action / Why / Purpose** block that distils the note's reasoning into "
            "something you can actually do._",
            "",
            "## Categories",
            "",
        ]
        for category in sorted(by_category):
            count = len(by_category[category])
            lines.append(f"- [{category}]({slugify(category)}.md) — {count} note{'s' if count != 1 else ''}")
        lines.append("")
        (out_dir / "index.md").write_text("\n".join(lines), encoding="utf-8")

    def _write_category(
        self,
        category: str,
        items: list[Note],
        all_notes: list[Note],
        out_dir: Path,
    ) -> None:
        lines = [f"# {category}", "", f"[← index](index.md)", ""]
        for note in sorted(items, key=lambda n: n.title.lower()):
            lines.extend(self._render_note(note, all_notes))
            lines.append("")
        path = out_dir / f"{slugify(category)}.md"
        path.write_text("\n".join(lines), encoding="utf-8")

    def _render_note(self, note: Note, all_notes: list[Note]) -> list[str]:
        slug = slugify(note.title)
        title_html = html.escape(note.title)

        body_html = "<br>".join(
            html.escape(line) for line in note.body.strip().splitlines() or [""]
        )
        sections: list[str] = [
            f'<div class="note-card" id="{slug}-card">',
            f'<h2 id="{slug}" class="note-card__title">{title_html}</h2>',
        ]
        if note.summary:
            sections.append(
                f'<p class="note-card__summary"><em>{html.escape(note.summary)}</em></p>'
            )
        sections.append(_section_html("orig", "Original note", body_html))
        sections.append(_section_html("act", "Action", html.escape(note.action.action)))
        sections.append(_section_html("why", "Why", html.escape(note.action.why)))
        sections.append(_section_html("pur", "Purpose", html.escape(note.action.purpose)))

        if note.versions:
            versions_html = "<br>".join(
                f"<strong>v{i}.</strong> {html.escape(v.strip())}"
                for i, v in enumerate(note.versions, 1)
            )
            sections.append(
                _section_html("ver", f"{len(note.versions)} merged versions", versions_html)
            )

        meta = self._meta_html(note, all_notes)
        if meta:
            sections.append(meta)
        sections.append("</div>")
        sections.append("")
        return sections

    def _meta_html(self, note: Note, all_notes: list[Note]) -> str:
        bits: list[str] = []
        if note.tags:
            tag_html = " ".join(
                f'<span class="nb-tag">#{html.escape(t)}</span>' for t in note.tags
            )
            bits.append(f'<span class="nb-meta-bit"><span class="nb-meta-key">Tags</span> {tag_html}</span>')
        if note.sources:
            src_html = ", ".join(
                f'<span class="nb-source">{html.escape(s)}</span>'
                for s in sorted(set(note.sources))
            )
            bits.append(f'<span class="nb-meta-bit"><span class="nb-meta-key">Source</span> {src_html}</span>')
        if note.devices:
            dev_html = ", ".join(
                f'<span class="nb-device">{html.escape(d)}</span>'
                for d in sorted(set(note.devices))
            )
            bits.append(f'<span class="nb-meta-bit"><span class="nb-meta-key">Device</span> {dev_html}</span>')
        backlinks = self._backlinks_for(note, all_notes)
        if backlinks:
            see_html = ", ".join(f'<em>{html.escape(t)}</em>' for t in backlinks)
            bits.append(f'<span class="nb-meta-bit"><span class="nb-meta-key">See also</span> {see_html}</span>')
        if not bits:
            return ""
        return f'<div class="nb-meta">{"".join(bits)}</div>'

    def _backlinks_for(self, note: Note, all_notes: list[Note]) -> list[str]:
        my_tags = set(note.tags)
        if not my_tags:
            return []
        related: list[str] = []
        for other in all_notes:
            if other.note_id == note.note_id:
                continue
            shared = my_tags & set(other.tags)
            if len(shared) >= self._min_shared:
                related.append(other.title)
        return sorted(related)[:5]
